laserscan_multi_merger:
  ros__parameters:
    destination_frame: "base_link"
    cloud_destination_topic: "/merged_cloud"
    scan_destination_topic: "/scan_multi"
    laserscan_topics: "/laser_scan_1 /laser_scan_2"
    angle_min: 0.0
    angle_max: 2.4
    angle_increment: 0.1
    #scan_time: 0.0
    range_min: 0.05
    range_max: 10.0

